import type { ProductFormValues, ProductStatus } from "./types";

export const defaultProductValues: ProductFormValues = {
  title: "",
  handle: "",
  description: "",
  descriptionHtml: "",
  price: 0,
  compareAtPrice: null,
  sku: "",
  inventory: 0,
  availableForSale: true,
  status: "ACTIVE" as ProductStatus,
  seoTitle: "",
  seoDescription: "",
  images: [],
  featuredImage: "",
  productType: "",
  categoryId: "",
  subcategoryId: "",
  vendor: "OrganoCity",
  tags: [],
  collectionIds: [],
  isFeatured: false,
  displayOrder: 1,
  details: [],
  color: "",
  size: "",
  storage: "",
  ram: "",
  processor: "",
  condition: "",
  specifications: {},
  customAttributes: {},
  variants: [],
};
